export const MONTH_UP = "MONTH_UP"
export const MONTH_DOWN = "MONTH_DOWN"

export const DATE_SELECT = "DATE_SELECT"


export const NOTE_SAVE = 'NOTE_SAVE'
export const NOTE_SAVE_REQUEST = 'NOTE_SAVE_REQUEST'
export const NOTE_SAVE_SUCCESS = 'NOTE_SAVE_SUCCESS'
export const NOTE_SAVE_FAIL = 'NOTE_SAVE_FAIL'

export const NOTE_DELETE = 'NOTE_DELETE'

export const NOTE_FETCH = 'NOTE_FETCH'
export const NOTE_REQUEST = 'NOTE_REQUEST'
export const NOTE_REQUEST_SUCCESS = 'NOTE_REQUEST_SUCCESS'
export const NOTE_REQUEST_FAIL  = 'NOTE_REQUEST_FAIL'

export const NOTE_SET = 'NOTE_SET'

export const NOTE_MONTH_FETCH = 'NOTE_MONTH_FETCH'
export const NOTE_MONTH_REQUEST = 'NOTE_MONTH_REQUEST'
export const NOTE_MONTH_REQUEST_SUCCESS = 'NOTE_MONTH_REQUEST_SUCCESS'
export const NOTE_MONTH_REQUEST_FAIL = 'NOTE_MONTH_REQUEST_FAIL'
export const NOTE_MONTH_SET = 'NOTE_MONTH_SET'

export const USER_LOGIN = 'USER_LOGIN'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS'
export const LOGIN_REQUEST_FAIL = 'LOGIN_REQUEST_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'
