export const MONTH_UP = "MONTH_UP"
export const MONTH_DOWN = "MONTH_DOWN"

export const DATE_SELECT = "DATE_SELECT"


export const NOTE_SAVE = 'NOTE_SAVE'
export const NOTE_DELETE = 'NOTE_DELETE'

export const NOTE_SAVE_ON_SERVER = 'NOTE_SAVE_ON_SERVER'

export const NOTE_FETCH = 'NOTE_FETCH'
export const NOTE_REQUEST = 'NOTE_REQUEST'
export const NOTE_REQUEST_SUCCESS = 'NOTE_REQUEST_SUCCESS'
export const NOTE_REQUEST_FAIL  = 'NOTE_REQUEST_FAIL'
