export const MONTH_UP = "MONTH_UP"
export const MONTH_DOWN = "MONTH_DOWN"

export const DATE_SELECT = "DATE_SELECT"


export const NOTE_SAVE = 'NOTE_SAVE'
export const NOTE_SAVE_REQUEST = 'NOTE_SAVE_REQUEST'
export const NOTE_SAVE_SUCCESS = 'NOTE_SAVE_SUCCESS'
export const NOTE_SAVE_FAIL = 'NOTE_SAVE_FAIL'

export const NOTE_DELETE = 'NOTE_DELETE'
export const NOTE_DELETE_REQUEST = 'NOTE_DELETE_REQUEST'
export const NOTE_DELETE_FAIL = 'NOTE_DELETE_FAIL'
export const NOTE_DELETE_SUCCESS = 'NOTE_DELETE_SUCCESS'

export const NOTE_FETCH = 'NOTE_FETCH'
export const NOTE_REQUEST = 'NOTE_REQUEST'
export const NOTE_REQUEST_SUCCESS = 'NOTE_REQUEST_SUCCESS'
export const NOTE_REQUEST_FAIL  = 'NOTE_REQUEST_FAIL'

export const NOTE_SET = 'NOTE_SET'

export const NOTE_MONTH_FETCH = 'NOTE_MONTH_FETCH'
export const NOTE_MONTH_REQUEST = 'NOTE_MONTH_REQUEST'
export const NOTE_MONTH_REQUEST_SUCCESS = 'NOTE_MONTH_REQUEST_SUCCESS'
export const NOTE_MONTH_REQUEST_FAIL = 'NOTE_MONTH_REQUEST_FAIL'
export const NOTE_MONTH_SET = 'NOTE_MONTH_SET'

export const USER_LOGIN = 'USER_LOGIN'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const USER_REGISTER = 'USER_REGISTER'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const CHECK_AUTH = ' CHECK_AUTH'

export const NOT_AUTHENTICATED = 'NOT_AUTHENTICATED'